import { useState, type FormEvent } from 'react'
import { Building2, MapPin, Package, Plus, ShieldAlert, UserRound } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { totalStock } from '../types'
import { currency, number } from '../utils'
import { Modal, Toast } from '../components/UI'

export function WarehousesPage() {
  const { warehouses, products, user, addWarehouse } = useApp()
  const [open, setOpen] = useState(false)
  const [toast, setToast] = useState('')
  const [denied, setDenied] = useState(false)
  const allUnits = products.reduce((sum, product) => sum + totalStock(product), 0)

  const requestCreate = () => user?.role === 'admin' ? setOpen(true) : setDenied(true)
  const saved = () => { setOpen(false); setToast('Warehouse created successfully'); setTimeout(() => setToast(''), 2600) }

  return <div className="page-stack"><div className="page-heading-row"><div><h2>Warehouse network</h2><p>Monitor inventory allocation and manage storage locations.</p></div><button className="button primary" onClick={requestCreate}><Plus size={18} /> Create warehouse</button></div><section className="warehouse-summary"><div><Building2 size={21} /><span><strong>{warehouses.length}</strong>Active warehouses</span></div><div><Package size={21} /><span><strong>{number.format(allUnits)}</strong>Total units stored</span></div><div><MapPin size={21} /><span><strong>{new Set(warehouses.map((warehouse) => warehouse.location.split(',').at(-1)?.trim())).size}</strong>Regions covered</span></div></section><section className="warehouse-card-grid">{warehouses.map((warehouse, index) => { const units = products.reduce((sum, product) => sum + (product.stocks[warehouse.id] ?? 0), 0); const value = products.reduce((sum, product) => sum + (product.stocks[warehouse.id] ?? 0) * product.cost, 0); const skus = products.filter((product) => (product.stocks[warehouse.id] ?? 0) > 0).length; return <article className="warehouse-card" key={warehouse.id}><div className={`warehouse-cover cover-${index % 3}`}><span>{warehouse.code}</span><Building2 size={40} /></div><div className="warehouse-card-body"><div className="warehouse-card-title"><div><h3>{warehouse.name}</h3><p><MapPin size={14} />{warehouse.location}</p></div><span className="online-dot">Active</span></div><div className="warehouse-metrics"><div><span>Units on hand</span><strong>{number.format(units)}</strong></div><div><span>Inventory value</span><strong>{currency.format(value)}</strong></div><div><span>Active SKUs</span><strong>{skus}</strong></div></div><div className="warehouse-manager"><div className="avatar small">{warehouse.manager.split(' ').map((part) => part[0]).join('')}</div><span><small>Warehouse manager</small><strong>{warehouse.manager}</strong></span></div><div className="warehouse-stock-preview"><span>Top inventory</span>{products.filter((product) => (product.stocks[warehouse.id] ?? 0) > 0).sort((a, b) => (b.stocks[warehouse.id] ?? 0) - (a.stocks[warehouse.id] ?? 0)).slice(0, 3).map((product) => <div key={product.id}><span>{product.name}</span><strong>{product.stocks[warehouse.id]} units</strong></div>)}</div></div></article> })}</section>{open && <WarehouseForm onClose={() => setOpen(false)} onSave={(input) => { addWarehouse(input); saved() }} />}{denied && <Modal title="Administrator access required" subtitle="Your role does not include warehouse configuration permissions." onClose={() => setDenied(false)}><div className="permission-message"><ShieldAlert size={36} /><p>Inventory managers can view stock across all locations, but only administrators can add warehouse records.</p><button className="button secondary" onClick={() => setDenied(false)}>Got it</button></div></Modal>}{toast && <Toast message={toast} />}</div>
}

function WarehouseForm({ onClose, onSave }: { onClose: () => void; onSave: (input: { code: string; name: string; location: string; manager: string }) => void }) {
  const [form, setForm] = useState({ code: '', name: '', location: '', manager: '' })
  const submit = (event: FormEvent) => { event.preventDefault(); onSave({ ...form, code: form.code.trim().toUpperCase() }) }
  return <Modal title="Create warehouse" subtitle="Add a new location to your inventory network." onClose={onClose}><form className="modal-form" onSubmit={submit}><div className="form-grid"><label className="field-label">Warehouse code<input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="CHI-01" required /></label><label className="field-label full">Warehouse name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Midwest Distribution" required /></label><label className="field-label full">Location<div className="input-with-icon"><MapPin size={17} /><input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="Chicago, Illinois" required /></div></label><label className="field-label full">Manager<div className="input-with-icon"><UserRound size={17} /><input value={form.manager} onChange={(e) => setForm({ ...form, manager: e.target.value })} placeholder="Full name" required /></div></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Create warehouse</button></div></form></Modal>
}
